import type { Metadata } from "next";
import { Nabla, Tourney } from "next/font/google"
import "./globals.css";

const nabla = Nabla({
  subsets: ['latin'],
  weight: '400',
});

const tourney = Tourney({
  subsets: ['latin'],
  weight: '900',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
